// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX3_anTxJY7T2fUeVh6x9O_i2XNaDX3gg',
    appId: '1:1016950343606:web:db4c93f03bdb3382da2317',
    messagingSenderId: '1016950343606',
    projectId: 'bmi-task-f72b8',
    authDomain: 'bmi-task-f72b8.firebaseapp.com',
    storageBucket: 'bmi-task-f72b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-bw_UGNZRW_8mI4IFTbMxPuSJVclSAg',
    appId: '1:1016950343606:android:b0e619f6dea1f906da2317',
    messagingSenderId: '1016950343606',
    projectId: 'bmi-task-f72b8',
    storageBucket: 'bmi-task-f72b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWkwJjttR5XR_MsdquAgL9p33eqRU-QM',
    appId: '1:1016950343606:ios:b9fd34626700616bda2317',
    messagingSenderId: '1016950343606',
    projectId: 'bmi-task-f72b8',
    storageBucket: 'bmi-task-f72b8.appspot.com',
    iosBundleId: 'com.example.bmiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWkwJjttR5XR_MsdquAgL9p33eqRU-QM',
    appId: '1:1016950343606:ios:b9fd34626700616bda2317',
    messagingSenderId: '1016950343606',
    projectId: 'bmi-task-f72b8',
    storageBucket: 'bmi-task-f72b8.appspot.com',
    iosBundleId: 'com.example.bmiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX3_anTxJY7T2fUeVh6x9O_i2XNaDX3gg',
    appId: '1:1016950343606:web:d706ad2ea586c798da2317',
    messagingSenderId: '1016950343606',
    projectId: 'bmi-task-f72b8',
    authDomain: 'bmi-task-f72b8.firebaseapp.com',
    storageBucket: 'bmi-task-f72b8.appspot.com',
  );
}
